name: event_hub
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  change_app_package_name: ^1.5.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  intl: 0.19.0
  external_path: ^2.2.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/