// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1qUN63Db05B8ST_l9NQY1akjZmqxG9M',
    appId: '1:1076801344887:web:70e390d6497d0ab3abbd72',
    messagingSenderId: '1076801344887',
    projectId: 'event-deeac',
    authDomain: 'event-deeac.firebaseapp.com',
    storageBucket: 'event-deeac.firebasestorage.app',
    measurementId: 'G-Q407CZY653',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhINZN_SThjzHGbJjJUDgWgvh5Q52Q40M',
    appId: '1:1076801344887:android:d11e320bca90eba8abbd72',
    messagingSenderId: '1076801344887',
    projectId: 'event-deeac',
    storageBucket: 'event-deeac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyExfnD3-lj27TQCK0xrxoD97ya_DyN0o',
    appId: '1:337599404062:ios:7f107d243dfc63ed73760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAheQlKbKAaEAw2V_nzj4kJkjTN7tIEKJo',
    appId: '1:1076801344887:ios:5110d502a9c86100abbd72',
    messagingSenderId: '1076801344887',
    projectId: 'event-deeac',
    storageBucket: 'event-deeac.firebasestorage.app',
    iosClientId: '1076801344887-0apajhb8fajnhlfeeivkdmlqsmcsaf51.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1qUN63Db05B8ST_l9NQY1akjZmqxG9M',
    appId: '1:1076801344887:web:fa46aac3a79e79d1abbd72',
    messagingSenderId: '1076801344887',
    projectId: 'event-deeac',
    authDomain: 'event-deeac.firebaseapp.com',
    storageBucket: 'event-deeac.firebasestorage.app',
    measurementId: 'G-L7RC9SRW7W',
  );

}